name: stripe_native
description: Create chargeable stripe tokens using Apple and Google Pay. Display native Apple and Google Pay sheets, then collect one-time source tokens.
version: 1.2.3
homepage: https://www.rbitwo.com
repository: https://github.com/rbii-incorporated/stripe_native

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rbitwo.stripe_native
        pluginClass: StripeNativePlugin
      ios:
        pluginClass: StripeNativePlugin

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.13.0 <2.0.0"